fields:
  country:
    label: Country
    help: Used to determine Shipping rates
    type: select
    options: query
    query:
      page: /shop/countries
      fetch: children
  discountcode:
    label: Discount code
    help: Use this discount code every time you log in. Letters and numbers only.
    type: text
    validate: alphanum


